enableTelemetry: false

nodeLinker: node-modules

plugins:
  - checksum: 37b2361b1502b2054e6779788c0e9bdd6a90ce49852a8cad2feda79b0614ec94f06fb6e78951f5f95429c610d7934dd077caa47413a0227378a102c55161616d
    path: .yarn/plugins/plugin-prepare-lifecycle.cjs
    spec: "https://github.com/un-es/yarn-plugin-prepare-lifecycle/releases/download/v0.0.1/index.js"

yarnPath: .yarn/releases/yarn-4.9.1.cjs
